# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/pixel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 660)
        self.label_show = QtWidgets.QLabel(Dialog)
        self.label_show.setGeometry(QtCore.QRect(0, 60, 600, 600))
        self.label_show.setScaledContents(True)
        self.label_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show.setObjectName("label_show")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 431, 60))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.label_path = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_path.setObjectName("label_path")
        self.horizontalLayout_1.addWidget(self.label_path)
        self.lineEdit_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_1.addWidget(self.lineEdit_path)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_interval = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_interval.setObjectName("label_interval")
        self.horizontalLayout_2.addWidget(self.label_interval)
        self.lineEdit_interval = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_interval.setObjectName("lineEdit_interval")
        self.horizontalLayout_2.addWidget(self.lineEdit_interval)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setCheckable(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.pushButton_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_2.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_Information = QtWidgets.QLabel(Dialog)
        self.label_Information.setGeometry(QtCore.QRect(430, 0, 170, 60))
        self.label_Information.setTextFormat(QtCore.Qt.RichText)
        self.label_Information.setScaledContents(False)
        self.label_Information.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Information.setObjectName("label_Information")
        self.label_Information.setWordWrap(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "图片 JSON 互转"))
        self.label_show.setText(_translate("Dialog", "预览图"))
        self.label_path.setText(_translate("Dialog", "图片/json 路径:"))
        self.lineEdit_path.setText(_translate("Dialog", "图片/json 路径"))
        self.label_interval.setText(_translate("Dialog", "采样间隔:"))
        self.lineEdit_interval.setText(_translate("Dialog", "3"))
        self.checkBox.setText(_translate("Dialog", "白色背景"))
        self.pushButton_1.setText(_translate("Dialog", "生成预览"))
        self.pushButton_2.setText(_translate("Dialog", "导出预览"))
        self.pushButton_3.setText(_translate("Dialog", "导出json"))
        self.label_Information.setText(_translate("Dialog", "信息:<br/>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
